import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/191a957bb7.js" crossOrigin ="anonymous" async></script>
      </Head>

      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}